### ISSUE TITLE
current version of deploy.zip has empty lib/ folder

### ISSUE THREAD

**Issue by midnightcodr** [Weswit/Lightstreamer-example-HelloWorld-adapter-node#3]
file ls-proxy-adapters.jar (which exists inside version 5.1 deploy.zip) is missing from the current version. Please add it. Hello world example gives out the following error in node:

Unexpected message ###|SUB|S|greetings while waiting for a DPI message

LS server spits out error like
Exception caught while subscribing to item 'greetings': Connection closed while waiting for an answer to request

**Comment by Bravo27** [comment]
Hi midnightcodr,

Please note that in Lightstreamer 6.0 the ls-proxy-adapters.jar file is no longer needed since the Proxy Adapters classes are been embedded into Lightstreamer server.

The error is due to using the Proxy Adapter of the 5.x version with the Remote interface of Lightstreamer 6.0 that which are no longer compatible.
If you are running Lighstreamer 6 you must also use the Proxy Adapter for 6.0 version (without ls-proxy-adapters.jar).

**Comment by midnightcodr** [comment]
OK my bad just found out we are using 5.1.2 on the server and I am using 5.1 deploy.zip but still there seems to be a problem with the node module, when I run helloworld.js I got

Error: Unexpected message 10000014ba2d8d77c|SUB|S|greetings while waiting for a DPI message
    at read (/Users/<user>/dev/node-ls/node_modules/lightstreamer-adapter/lib/dataprotocol.js:191:9)
    at Object.parse (/Users/<user>/dev/node-ls/node_modules/lightstreamer-adapter/lib/protocol.js:317:18)
    at Socket.handleIncomingMessage (/Users/<user>/dev/node-ls/node_modules/lightstreamer-adapter/lib/dataprovider.js:88:10)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

**Comment by Bravo27** [comment]
Are you using the helloworld.js from "Release for Lightstreamer 5.1"(https://github.com/Weswit/Lightstreamer-example-HelloWorld-adapter-node/releases/tag/for_Lightstreamer_5.1)?

**Comment by midnightcodr** [comment]
OK I found the problem, "npm install lightstreamer-adapter" installs the newest version of npm package that works with LS 6. For now I just copy the files from DOCS-SDKs/sdk_adapter_nodejs/lib on the server to replace files under node_modules/lightstreamer-adapter/lib on my node server. Problem is fixed. Thank you very much for your help.

**Comment by Bravo27** [comment]
Hi midnightcodr,

Thank you for feedback. Actually, an addition to the release notes for "Release for Lightstreamer 5.1" was needed. Now I have added an example of npm command to install the correct version (1.0.2) of the lightstreamer-adapter package when using Lighstreamer 5.x.

`>npm install lightstreamer-adapter@1.0.2`
